version: '3'

services:
    redis:
        container_name: redis-systematica
        image: redis:alpine
        ports:
            - 6380:6379
        restart: unless-stopped
    mysql:
        container_name: mysql-systematica
        image: mysql:5.7
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "systematica"

        restart: unless-stopped
    server:
        container_name: server-systematica
        build:
            context: ./server
            dockerfile: Dockerfile
        image: development
        ports:
            - 3001:3001
        depends_on:
            - redis
            - mysql
        restart: unless-stopped
    app:
        container_name: app-systematica
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - server
        restart: unless-stopped
        command: npm run dev -- --host --port 3000
