version: '3'

services:
    redis:
        container_name: redis-kingspan
        image: redis:alpine
        ports:
            - 6380:6379
        restart: unless-stopped
    mysql:
        container_name: mysql-kingspan
        image: mysql:5.7
        ports:
            - 3309:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        restart: unless-stopped
